<?php

// Exit (success)
return [
	// System
	'svoboda' => 'Svoboda',
	'empty' => 'Empty',
	'yes' => 'Yes',
	'no' => 'No',

	// Main menu
	'menu_title' => 'Main menu',
	'menu_accounts' => 'Accounts',
	'menu_members' => 'Members',
	'menu_distributions' => 'Distributions',
	'menu_not_syncronized' => 'The database does not synchronize with the blockchain network',
	'menu_button_site' => 'Site',
	'menu_button_map' => 'Map',
	'menu_button_blog' => 'Blog',
	'menu_button_projects' => 'Projects',
	'menu_button_members' => 'Members',
	'menu_button_distributions' => 'Distributions',

	// Members
	'members_title' => 'Registry of members',
	'members_description' => 'Member is a person who has any form of affiliation with *Svoboda*',
	'members_button_search' => 'Search',

	// Members search
	'member_search_started' => 'Process of the member search started',
	'member_search_not_started' => 'Process of the member search has not started',
	'member_search_ended' => 'Process of the member search ended',
	'member_search_not_localized' => 'Failed to initialize the member account localization',
	'member_search_not_named' => 'No name',
	'member_search_status' => 'Status',
	'member_search_status_2' => 'Member',
	'member_search_status_1' => 'Planned',
	'member_search_status_0' => 'Unknown',
	'member_search_continiued' => 'Process of the member search found and continiued',
	'member_search_empty' => 'No members found',
	'member_search_title' => 'Member search',
	'member_search_distribution' => 'Distribution',
	'member_search_page_next_exists' => 'There are more members in the registry',
	'member_search_page_next_not_exists' => 'There are no more members in the registry',
	'member_search_button_name' => 'Name',
	'member_search_name_request_title' => 'Enter name',
	'member_search_name_request_description' => 'Search will be conducted by members names using the Levenshtein function',
	'member_search_name_request_not_acceptable' => 'Failed to process the name',
	'member_search_name_request_too_short' => 'Name length must be \>\= 2 and \<\= 128',
	'member_search_name_request_too_long' => 'Name length must be \>\= 2 and \<\= 128',
	'member_search_name_request_restricted_characters_title' => "Restricted any characters except letters, dashes and spaces",
	'member_search_name_request_restricted_characters_description' => "Remove these characters:",
	'member_search_name_update_success' => 'Name replaced:',
	'member_search_name_update_fail' => 'Failed to replace name',
	'member_search_distribution_selection_description' => 'The selected distribution will be used to search for members',
	'member_search_distribution_update_success' => 'Distribution replaced:',
	'member_search_distribution_update_fail' => 'Failed to replace distribution',
	'member_search_status_select_title' => 'Select the member status',
	'member_search_status_update_success' => 'Status replaced:',
	'member_search_status_update_fail' => 'Failed to replace status',
	'member_search_button_start' => 'Start the search',
	'member_search_button_end' => 'End the search',
	'member_search_button_page_next' => 'Next page',
	'member_search_button_message' => 'Message',
	'member_search_button_distribution' => 'Distribution',
	'member_search_button_status' => 'Status',
	'member_search_button_status_2' => 'Member',
	'member_search_button_status_1' => 'Planned',
	'member_search_button_status_0' => 'Unknown',

	// Distributions
	'distributions_title' => 'Registry of distributions',
	'distributions_description' => '*Distribution* is an autonomous cell of Svoboda, representing any type of formation \(for example: commune\), but necessarily inherits the *Vhod* protocol and tied to a location',
	'distributions_declared' => 'Declared',
	'distributions_recognized' => 'Recognized',
	'distributions_button_search' => 'Search',
	'distributions_button_declare' => 'Declare',

	// Distribution selection
	/* 'select_distributions_title' => 'Select distribution',
	'select_distributions_description' => 'The selected distribution will be used in the current process',
	'select_distribution_button_registrate' => 'Registrate a distribution', */

	// Distribution declaration
	'distribution_declaration_started' => 'Process of the distribution declaration started',
	'distribution_declaration_not_started' => 'Process of the distribution declaration has not started',
	'distribution_declaration_ended' => 'Process of the distribution declaration ended',
	'distribution_declaration_continiued' => 'Process of the distribution declaration found and continiued',
	'distribution_declaration_generation' => 'The distribution record generation',
	'distribution_declaration_created_distribution' => 'Created the distribution record in the database',
	'distribution_declaration_created_localization' => 'Created the distribution localization record in the database',
	'distribution_declaration_canceled' => 'Process of the distribution declaration canceled',
	'distribution_declaration_completed' => 'Process of the distribution declaration completed',
	'distribution_declaration_not_created_distribution' => 'Failed to create the distribution record in the database',
	'distribution_declaration_not_created_localization' => 'Failed to create the distribution localization record in the database',
	'distribution_declaration_button_language' => 'Language',
	'distribution_declaration_select_language_title' => 'Choose a language',
	'distribution_declaration_select_language_description' => "The selected language will create a localization for users with the same language\n\nYou can create 1 localization for each language",
	'distribution_declaration_language_update_success' => 'Language replaced:',
	'distribution_declaration_language_update_fail' => 'Failed to replace language',
	'distribution_declaration_button_name' => 'Name',
	'distribution_declaration_name_request' => 'Enter name',
	'distribution_declaration_name_request_not_acceptable' => 'Failed to process the name',
	'distribution_declaration_name_request_too_short' => 'Name length must be \>\= 3 and \<\= 64',
	'distribution_declaration_name_request_too_long' => 'Name length must be \>\= 3 and \<\= 64',
	'distribution_declaration_name_request_spaces' => "No more than 2 spaces are allowed",
	'distribution_declaration_name_request_restricted_characters_title' => "Restricted any characters except letters",
	'distribution_declaration_name_request_restricted_characters_description' => "Remove these characters:",
	'distribution_declaration_name_update_success' => 'Name replaced:',
	'distribution_declaration_name_update_fail' => 'Failed to replace name',
	'distribution_declaration_button_location' => 'Location',
	'distribution_declaration_button_location_send' => 'Send location',
	'distribution_declaration_location_send_title' => 'Send location',
	'distribution_declaration_location_send_description' => "You now have a button on your main keyboard\nWhen you click on it, you can select a location on the map\n\n*Send latitude and longitude in the format:* 50\.969043, 9\.797588",
	'distribution_declaration_location_send_not_acceptable' => 'Failed to process the location',
	'distribution_declaration_location_send_latitude_too_small' => 'Latitude must be \>\= 0 and \<\=90',
	'distribution_declaration_location_send_latitude_too_big' => 'Latitude must be \>\= 0 and \<\=90',
	'distribution_declaration_location_send_longitude_too_small' => 'Longitude must be \>\= 0 and \<\=180',
	'distribution_declaration_location_send_longitude_too_big' => 'Longitude must be \>\= 0 and \<\=180',
	'distribution_declaration_location_update_success' => 'Location replaced:',
	'distribution_declaration_location_update_fail' => 'Failed to replace location',
	'distribution_declaration_button_confirm' => 'Confirm',
	'distribution_declaration_button_cancel' => 'Cancel',

	// Distribution localization
	'distribution_localization_started' => 'declaration of the distribution process started',
	'distribution_localization_continiued' => 'declaration of the distribution process found and continiued',
	'distribution_localization_created' => 'Created the distribution localization record in the database',
	'distribution_localization_not_created' => 'Failed to create the distribution localization record in the database',
	'distribution_localization_select_language_title' => 'Choose a language',
	'distribution_localization_select_language_description' => "The selected language will create a localization for users with the same language\n\nYou can create 1 localization for each language",

	// Distribution search
	'distribution_search_started' => 'Process of the distribution search started',
	'distribution_search_not_started' => 'Process of the distribution search has not started',
	'distribution_search_ended' => 'Process of the distribution search ended',
	'distribution_search_not_localized' => 'Failed to initialize the distribution localization',
	'distribution_search_not_named' => 'No name',
	'distribution_search_continiued' => 'Process of the distribution search found and continiued',
	'distribution_search_empty' => 'No distributions found',
	'distribution_search_title' => 'Distribution search',
	'distribution_search_members' => 'Members',
	'distribution_search_recognized' => 'Recognized',
	'distribution_search_planners' => 'Planners',
	'distribution_search_volunteers' => 'Volunteers',
	'distribution_search_messages' => 'Messages',
	'distribution_search_location' => 'Location',
	'distribution_search_page_next_exists' => 'There are more distributions in the registry',
	'distribution_search_page_next_not_exists' => 'There are no more distributions in the registry',
	'distribution_search_button_name' => 'Name',
	'distribution_search_name_request_title' => 'Enter name',
	'distribution_search_name_request_description' => 'Search will be conducted by distributions names using the Levenshtein function',
	'distribution_search_name_request_not_acceptable' => 'Failed to process the name',
	'distribution_search_name_request_too_short' => 'Name length must be \>\= 3 and \<\= 64',
	'distribution_search_name_request_too_long' => 'Name length must be \>\= 3 and \<\= 64',
	'distribution_search_name_request_restricted_characters_title' => "Restricted any characters except letters",
	'distribution_search_name_request_restricted_characters_description' => "Remove these characters:",
	'distribution_search_name_update_success' => 'Name replaced:',
	'distribution_search_name_update_fail' => 'Failed to replace name',
	'distribution_search_button_location' => 'Location',
	'distribution_search_button_location_send' => 'Send location',
	'distribution_search_location_send_title' => 'Send location',
	'distribution_search_location_send_description' => "You now have a button on your main keyboard\nWhen you click on it, you can select a location on the map\n\n*Send latitude and longitude in the format:* 50\.969043, 9\.797588",
	'distribution_search_location_send_not_acceptable' => 'Failed to process the location',
	'distribution_search_location_send_latitude_too_small' => 'Latitude must be \>\= 0 and \<\=90',
	'distribution_search_location_send_latitude_too_big' => 'Latitude must be \>\= 0 and \<\=90',
	'distribution_search_location_send_longitude_too_small' => 'Longitude must be \>\= 0 and \<\=180',
	'distribution_search_location_send_longitude_too_big' => 'Longitude must be \>\= 0 and \<\=180',
	'distribution_search_location_update_success' => 'Location replaced:',
	'distribution_search_location_update_fail' => 'Failed to replace location',
	'distribution_search_button_distance' => 'Distance',
	'distribution_search_distance_request_title' => 'Enter distance',
	'distribution_search_distance_request_description' => 'Search will be performed within a radius of this value using the Vincenty formula',
	'distribution_search_distance_request_not_acceptable' => 'Failed to process the distance',
	'distribution_search_distance_request_too_short_km' => 'Distance value must be \>\= 0 and \<\= 600',
	'distribution_search_distance_request_too_long_km' => 'Distance value must be \>\= 0 and \<\= 600',
	'distribution_search_distance_request_restricted_characters_title' => "Restricted any characters except digitals",
	'distribution_search_distance_request_restricted_characters_description' => "Delete these characters:",
	'distribution_search_distance_update_success' => 'Distance replaced:',
	'distribution_search_distance_update_fail' => 'Failed to replace distance',
	'distribution_search_button_start' => 'Start the search',
	'distribution_search_button_end' => 'End the search',
	'distribution_search_button_page_next' => 'Next page',
	'distribution_search_button_map' => 'Map',
	'distribution_search_button_members' => 'Members',
	'distribution_search_button_volunteers' => 'Volunteers',
	'distribution_search_button_plan' => 'Plan',
	'distribution_search_button_unplan' => 'Cancel the planning',
	'distribution_search_planned' => 'You planned to join to the distribution',
	'distribution_search_already_planned' => 'You are already planned to join to the distribution',
	'distribution_search_unplanned' => 'You canceled planning to join to the distribution',
	'distribution_search_already_unplanned' => 'You are already canceled planning to join to the distribution',
	'distribution_search_button_join' => 'Join',
	'distribution_search_button_leave' => 'Leave',
	'distribution_search_joined_title' => 'You joined the distribution',
	'distribution_search_joined_description' => 'You have claimed to be a member of the distribution, now you need to get recognition from its members',
	'distribution_search_already_joined' => 'You are already joined to the distribution',
	'distribution_search_leaved' => 'You leaved the distribution',
	'distribution_search_already_leaved' => 'You are already leaved the distribution',
	'distribution_search_button_message' => 'Message',
	'distribution_search_km' => 'km',
	'distribution_search_mi' => 'ml',
	'distribution_search_member_not_updated' => 'Failed to update the member record in the database',
	'distribution_search_member_not_created' => 'Failed to create the member record in the database',
	'distribution_search_distribution_not_initialized' => 'Failed to initalize the distribution',
	'distribution_search_message_not_initialized' => 'Failed to initialized the message',
	'distribution_search_another_joined' => 'You are already a member of another distribution',
	'distribution_search_another_planned' => 'You are already planning to join another distribution',

	// Distribution select
	'distribution_select_started' => 'Process of the distribution selection started',
	'distribution_select_not_started' => 'Process of the distribution selection has not started',
	'distribution_select_ended' => 'Process of the distribution selection ended',
	'distribution_select_not_localized' => 'Failed to initialize the distribution localization',
	'distribution_select_not_named' => 'No name',
	'distribution_select_continiued' => 'Process of the distribution select found and continiued',
	'distribution_select_empty' => 'No distributions found',
	'distribution_select_title' => 'Distribution selection',
	'distribution_select_button_name' => 'Name',
	'distribution_select_name_request_title' => 'Enter name',
	'distribution_select_name_request_description' => 'Selection will be conducted by distributions names using the Levenshtein function',
	'distribution_select_name_request_not_acceptable' => 'Failed to process the name',
	'distribution_select_name_request_too_short' => 'Name length must be \>\= 3 and \<\= 64',
	'distribution_select_name_request_too_long' => 'Name length must be \>\= 3 and \<\= 64',
	'distribution_select_name_request_restricted_characters_title' => "Restricted any characters except letters",
	'distribution_select_name_request_restricted_characters_description' => "Remove these characters:",
	'distribution_select_name_update_success' => 'Name replaced:',
	'distribution_select_name_update_fail' => 'Failed to replace name',
	'distribution_select_button_location' => 'Location',
	'distribution_select_button_location_send' => 'Send location',
	'distribution_select_location_send_title' => 'Send location',
	'distribution_select_location_send_description' => "You now have a button on your main keyboard\nWhen you click on it, you can select a location on the map\n\n*Send latitude and longitude in the format:* 50\.969043, 9\.797588",
	'distribution_select_location_send_not_acceptable' => 'Failed to process the location',
	'distribution_select_location_send_latitude_too_small' => 'Latitude must be \>\= 0 and \<\=90',
	'distribution_select_location_send_latitude_too_big' => 'Latitude must be \>\= 0 and \<\=90',
	'distribution_select_location_send_longitude_too_small' => 'Longitude must be \>\= 0 and \<\=180',
	'distribution_select_location_send_longitude_too_big' => 'Longitude must be \>\= 0 and \<\=180',
	'distribution_select_location_update_success' => 'Location replaced:',
	'distribution_select_location_update_fail' => 'Failed to replace location',
	'distribution_select_page_next_exists' => 'There are more distributions in the registry',
	'distribution_select_page_next_not_exists' => 'There are no more distributions in the registry',
	'distribution_select_button_distance' => 'Distance',
	'distribution_select_distance_request_title' => 'Enter distance',
	'distribution_select_distance_request_description' => 'Selection will be performed within a radius of this value using the Vincenty formula',
	'distribution_select_distance_request_not_acceptable' => 'Failed to process the distance',
	'distribution_select_distance_request_too_short_km' => 'Distance value must be \>\= 0 and \<\= 600',
	'distribution_select_distance_request_too_long_km' => 'Distance value must be \>\= 0 and \<\= 600',
	'distribution_select_distance_request_restricted_characters_title' => "Restricted any characters except digitals",
	'distribution_select_distance_request_restricted_characters_description' => "Delete these characters:",
	'distribution_select_distance_update_success' => 'Distance replaced:',
	'distribution_select_distance_update_fail' => 'Failed to replace distance',
	'distribution_select_button_delete' => 'Delete',
	'distribution_select_button_cancel' => 'Cancel',
	'distribution_select_button_page_next' => 'Next page',
	'distribution_select_button_select' => 'Select',
	'distribution_select_km' => 'km',
	'distribution_select_mi' => 'ml',

	// Account
	'account_title' => 'Account',
	'account_export' => 'This account can be exported to the Svoboda main blockchain network in the future',
	'account_data' => "⚠️ Your data may be given to the special services of Russia\nBe careful and think with your head.",
	'account_security_repository' => 'Information security',
	'account_security_repository_mirror_github' => 'mirror',
	'account_authorized_system' => 'Access to the system',
	'account_authorized_messages' => 'Access to messages',
	'account_authorized_joins' => 'Access to joins',
	'account_authorized_settings' => 'Access to settings',
	'account_authorized_system_accounts' => 'System access to accounts management',
	'account_authorized_system_distributions' => 'System access to distributions management',
	'account_authorized_system_members' => 'System access to members management',
	'account_authorized_system_settings' => 'System access to system settings',
	'account_button_localizations' => 'Localizations',
	'account_localization_create_failted_to_initialize_language' => 'Failed to initialize language',

	'account_localization_title' => 'Localizations',
	'account_localization_amount' => 'Amount',
	'account_localization_create' => 'Create a localization',
	'account_localization_create_started' => 'Process of the account localization creating started',
	'account_localization_create_not_started' => 'Process of the account localization creating not started',
	'account_localization_create_ended' => 'Process of the account localization creating ended',
	'account_localization_create_continiued' => 'Process of the account localization creating found and continiued',
	'account_localization_create_generation' => 'The account localization record generation',
	'account_localization_create_created' => 'Created the account localization record in the database',
	'account_localization_create_canceled' => 'Process of the account localization creating canceled',
	'account_localization_create_completed' => 'Process of the account localization creating completed',
	'account_localization_create_not_created' => 'Failed to create the account localization record in the database',
	'account_localization_create_every_language_created' => 'Localizations have already been created for all languages existing in the registry',
	'account_localization_create_button_language' => 'Language',
	'account_localization_create_select_language_title' => 'Choose a language',
	'account_localization_create_select_language_description' => "The selected language will be used when creating the account localization\n\nYou can create 1 localization for each language",
	'account_localization_create_language_update_success' => 'Language replaced:',
	'account_localization_create_language_update_fail' => 'Failed to replace language',
	'account_localization_create_button_name' => 'Name',
	'account_localization_create_name_request' => 'Enter name',
	'account_localization_create_name_request_not_acceptable' => 'Failed to process the name',
	'account_localization_create_name_request_too_short' => 'Name length must be \>\= 2 and \<\= 128',
	'account_localization_create_name_request_too_long' => 'Name length must be \>\= 2 and \<\= 128',
	'account_localization_create_name_request_restricted_characters_title' => "Restricted any characters except letters, dashes and spaces",
	'account_localization_create_name_request_restricted_characters_description' => "Remove these characters:",
	'account_localization_create_name_update_success' => 'Name replaced:',
	'account_localization_create_name_update_fail' => 'Failed to replace name',
	'account_localization_create_button_confirm' => 'Confirm',
	'account_localization_create_button_cancel' => 'Cancel',
	'account_localization_update_started' => 'Process of the account localization updating started',
	'account_localization_update_not_started' => 'Process of the account localization updating not started',
	'account_localization_update_ended' => 'Process of the account localization updating ended',
	'account_localization_update_continiued' => 'Process of the account localization updating found and continiued',
	'account_localization_update_generation' => 'The account localization record generation',
	'account_localization_update_generation_target' => 'Editing',
	'account_localization_update_updated' => 'Updated the account localization record in the database',
	'account_localization_update_canceled' => 'Process of the account localization updating canceled',
	'account_localization_update_completed' => 'Process of the account localization updating completed',
	'account_localization_update_not_updated' => 'Failed to update the account localization record in the database',
	'account_localization_update_not_initialized_localization' => 'Failed to initialize the account localization from the database',
	'account_localization_update_button_name' => 'Name',
	'account_localization_update_name_request' => 'Enter name',
	'account_localization_update_name_request_not_acceptable' => 'Failed to process the name',
	'account_localization_update_name_request_too_short' => 'Name length must be \>\= 2 and \<\= 128',
	'account_localization_update_name_request_too_long' => 'Name length must be \>\= 2 and \<\= 128',
	'account_localization_update_name_request_restricted_characters_title' => "Restricted any characters except letters, dashes and spaces",
	'account_localization_update_name_request_restricted_characters_description' => "Remove these characters:",
	'account_localization_update_name_update_success' => 'Name replaced:',
	'account_localization_update_name_update_fail' => 'Failed to replace name',
	'account_localization_update_button_confirm' => 'Confirm',
	'account_localization_update_button_cancel' => 'Cancel',
	'account_localization_search' => 'search',

	// Language setting
	'settings_select_language_title' => 'Select language',
	'settings_select_language_description' => 'The selected language will be writed in your account settings',
	'settings_language_update_success' => 'Language replaced:',
	'settings_language_update_fail' => 'Failed to replace language',

	// Language selection
	'select_language_title' => 'Select language',
	'select_language_description' => 'The selected language will be used in the current process',
	'select_language_button_add' => 'Add a language',

	// Repository
	'repository_title' => 'Repository',
	'repository_text' => <<<TXT
	Svoboder is written in [PHP](https://www.php.net/) using [Zanzara](https://github.com/badfarm/zanzara) for Telegram,
	my [MINIMAL](https://git.svoboda.works/mirzaev/minimal) framework for PHP and my [Baza](https://git.svoboda.works/mirzaev/baza) database

	The code is under the [WTFPL](https://en.wikipedia.org/wiki/WTFPL) license
	You can help me with the development, or use my code for free\!
	TXT,
	'repository_button_code' => 'The code',
	'repository_button_issues' => 'Issues',
	'repository_button_suggestions' => 'Suggestions',

	// Author
	'author_title' => 'Author',
	'author_text' => <<<TXT
	*Arsen Mirzaev Tatyano\-Muradovich*
	Programmer, anarchist, vegetarian
	TXT,
	'author_button_neurojournal' => 'Neurojournal',
	'author_button_projects' => 'Projects',
	'author_button_twitter' => 'Twitter',
	'author_button_bluesky' => 'Bluesky',
	'author_button_bastyon' => 'Bastyon',
	'author_button_youtube_english' => 'YouTube',
	'author_button_youtube_russian' => 'YouTube',
	'author_button_message' => 'Send a message',

	// Authorization
	'not_authorized_system' => 'You do not have access to the system',
	'not_authorized_messages' => 'You do not have access to send messages',
	'not_authorized_joins' => 'You do not have access to joins',
	'not_authorized_settings' => 'You do not have access to the settings',
	'not_authorized_system_settings' => 'You do not have access to the system settings',
	'not_authorized_system_distributions' => 'You do not have access to distributions administration',

	// Other
	'why_so_shroomious' => 'why so shroomious',
];
