<?php
define('MENU_MEMBERS_AMOUNT', 10000000);

define('DISTRIBUTIONS_SEARCH_PAGE', 3);
define('DISTRIBUTIONS_SEARCH_DISTRIBUTION_DISTANCE', 300);
define('DISTRIBUTIONS_SEARCH_DISTRIBUTION_LOCALIZATIONS_AMOUNT', 100);
define('DISTRIBUTIONS_SEARCH_DISTRIBUTION_NAME_LEVENSHTEIN_DISTANCE', 4);
define('DISTRIBUTIONS_SEARCH_MEMBER_DEPRECATING_RECORDS_AMOUNT', 500);
define('DISTRIBUTIONS_SEARCH_MEMBERS_AMOUNT', 10000000);

define('DISTRIBUTIONS_SELECT_PAGE', 10);
define('DISTRIBUTIONS_SELECT_DISTRIBUTION_DISTANCE', 300);
define('DISTRIBUTIONS_SELECT_DISTRIBUTION_LOCALIZATIONS_AMOUNT', 100);
define('DISTRIBUTIONS_SELECT_DISTRIBUTION_NAME_LEVENSHTEIN_DISTANCE', 4);
define('DISTRIBUTIONS_SELECT_MEMBER_DEPRECATING_RECORDS_AMOUNT', 500);
define('DISTRIBUTIONS_SELECT_MEMBERS_AMOUNT', 10000000);

define('MEMBERS_SEARCH_PAGE', 3);
define('MEMBERS_SEARCH_DISTRIBUTION_LOCALIZATIONS_AMOUNT', 100);
define('MEMBERS_SEARCH_ACCOUNT_LOCALIZATIONS_AMOUNT', 100);
define('MEMBERS_SEARCH_MEMBER_NAME_LEVENSHTEIN_DISTANCE', 4);
define('MEMBERS_SEARCH_STATUS_ROW_AMOUNT', 3);

define('ACCOUNT_LOCALIZATION_ACCOUNT_LOCALIZATIONS_AMOUNT', 100);
define('ACCOUNT_LOCALIZATION_CREATE_ACCOUNT_LOCALIZATIONS_AMOUNT', 100);
