<?php

// Exit (success)
return [
	// Система
	'svoboda' => 'Свобода',
	'antivertical' => 'Антивертикаль',
	'empty' => 'Пусто',
	'yes' => 'Да',
	'no' => 'Нет',

	// Главное меню
	'menu_title' => 'Антивертикаль',
	'menu_accounts' => 'Аккаунты',
	'menu_distributions' => 'Дистрибутивы',
	'menu_structors' => 'Структоры',
	'menu_autonoms' => 'Автономы',
	'menu_volunteers' => 'Волонтёры',
	'menu_investors' => 'Инвесторы',
	'menu_recruiters' => 'Вербовщики',
	/* 'menu_' => '', */
	'menu_not_syncronized' => 'База данных не синхронизирована с блокчейн сетью',
	'menu_warning_database' => 'База данных публикуется в репозиторий ежедневно',
	'menu_button_channel' => 'Канал',
	'menu_button_site' => 'Сайт',
	'menu_button_map' => 'Карта',
	'menu_button_blog' => 'Блог',
	'menu_button_chats' => 'Чаты',
	'menu_button_channels' => 'Каналы',
	'menu_button_memberships' => 'Участники',
	'menu_button_distributions' => 'Дистрибутивы',
	'menu_button_projects' => 'Проекты',
	'menu_button_events' => 'События',
	'menu_button_organisation' => 'Организация',

	// Думающие штуки
	'thing_about_it_1' => 'Великие имена создаются на востоке',
	'thing_about_it_1_author' => 'Лермонтов М. Ю.',
	'thing_about_it_2' => '',
	'thing_about_it_3' => '',
	'thing_about_it_4' => '',
	'thing_about_it_5' => '',
	/* 'thing_about_it_' => '',
	'thing_about_it__author' => '', */

	// Участники
	'memberships_title' => 'Реестр участников',
	'memberships_structor' => '*Структор* \- анархист, представляющий дистрибутив',
	'memberships_autonom' => '*Автоном* \- анархист, представляющий только себя лично',
	'memberships_button_search' => 'Поиск',

	// Поиск участника
	'membership_search_started' => 'Процесс поиска участника дистрибутива запущен',
	'membership_search_not_started' => 'Процесс поиска участника дистрибутива не запущен',
	'membership_search_ended' => 'Процесс поиска участника дистрибутива завершён',
	'membership_search_not_localized' => 'Не удалось инициализировать локализацию аккаунта участника',
	'membership_search_not_named' => 'Нет имени',
	'membership_search_status' => 'Статус',
	'membership_search_status_2' => 'Участие',
	'membership_search_status_2_emoji' => '🧳',
	'membership_search_status_1' => 'Планирование',
	'membership_search_status_1_emoji' => '📅',
	'membership_search_status_0' => 'Неизвестно',
	'membership_search_status_0_emoji' => '👽',
	'membership_search_continiued' => 'Процесс поиска участника дистрибутива найден и продолжен',
	'membership_search_empty' => 'Не найдены участники дистрибутивов',
	'membership_search_title' => 'Поиск участника дистрибутива',
	'membership_search_distribution' => 'Дистрибутив',
	'membership_search_page_next_exists' => 'В реестре есть ещё участники дистрибутивов',
	'membership_search_page_next_not_exists' => 'В реестре больше нет участников дистрибутивов',
	'membership_search_button_name' => 'Имя',
	'membership_search_name_request_title' => 'Введи имя',
	'membership_search_name_request_description' => 'Поиск будет проводиться по именам участников дистрибутивов с использованием функции Левенштейна',
	'membership_search_name_request_not_acceptable' => 'Не удалось обработать имя',
	'membership_search_name_request_too_short' => 'Длина имени должна быть \>\= 2 и \<\= 128',
	'membership_search_name_request_too_long' => 'Длина имени должна быть \>\= 2 и \<\= 128',
	'membership_search_name_request_restricted_characters_title' => "Запрещены любые символы кроме букв",
	'membership_search_name_request_restricted_characters_description' => "Удали эти символы:",
	'membership_search_name_update_success' => 'Имя заменено:',
	'membership_search_name_update_fail' => 'Не удалось заменить имя',
	'membership_search_button_start' => 'Начать поиск',
	'membership_search_button_end' => 'Завершить поиск',
	'membership_search_button_page_next' => 'Следующая страница',
	'membership_search_button_message' => 'Сообщение',
	'membership_search_button_distribution' => 'Дистрибутив',
	'membership_search_button_status' => 'Статус',
	'membership_search_button_status_2' => 'участие',
	'membership_search_button_status_2_emoji' => '🧳',
	'membership_search_button_status_1' => 'планирование',
	'membership_search_button_status_1_emoji' => '📅',
	'membership_search_button_status_0' => 'неизвестно',
	'membership_search_button_status_0_emoji' => '👽',

	// Дистрибутивы
	'distributions_title' => 'Реестр дистрибутивов',
	'distributions_description' => '*Дистрибутив* \- автономная ячейка Свободы, являющаяся любым видом формирования, подразумевающее безоговорочный солидарный союз со всеми признанными дистрибутивами внутри организации',
	'distributions_declared' => 'Объявленные',
	'distributions_recognized' => 'Признанные',
	'distributions_button_search' => 'Поиск',
	'distributions_button_declare' => 'Объявить',

	// Выбор дистрибутива
	/* 'select_distributions_title' => 'Выбери дистрибутив',
	'select_distributions_description' => 'Выбранный дистрибутив будет использован в текущем процесса',
	'select_distribution_button_registrate' => 'Зарегистрировать дистрибутив', */

	// Объявление дистрибутива
	'distribution_declaration_started' => 'Процесс объявления дистрибутива запущен',
	'distribution_declaration_not_started' => 'Процесс объявления дистрибутива не запущен',
	'distribution_declaration_ended' => 'Процесс объявления дистрибутива завершён',
	'distribution_declaration_continiued' => 'Процесс объявления дистрибутива найден и продолжен',
	'distribution_declaration_generation' => 'Генерация записи дистрибутива',
	'distribution_declaration_created_distribution' => 'Создана запись дистрибутива в базе данных',
	'distribution_declaration_created_localization' => 'Создана запись локализации дистрибутива в базе данных',
	'distribution_declaration_canceled' => 'Процесс объявления дистрибутива отменён',
	'distribution_declaration_completed' => 'Процесс объявления дистрибутива завершен',
	'distribution_declaration_not_created_distribution' => 'Не удалось создать запись дистрибутива в базе данных',
	'distribution_declaration_not_created_localization' => 'Не удалось создать запись локализации дистрибутива в базе данных',
	'distribution_declaration_button_language' => 'Язык',
	'distribution_declaration_select_language_title' => 'Выбери язык',
	'distribution_declaration_select_language_description' => "Выбранный язык позволит создать локализацию для пользователей с таким же языком\n\nТы можешь создать 1 локализацию для каждого языка",
	'distribution_declaration_language_update_success' => 'Язык заменён:',
	'distribution_declaration_language_update_fail' => 'Не удалось заменить язык',
	'distribution_declaration_button_name' => 'Название',
	'distribution_declaration_name_request' => 'Введи название',
	'distribution_declaration_name_request_not_acceptable' => 'Не удалось обработать название',
	'distribution_declaration_name_request_too_short' => 'Длина имени должна быть \>\= 3 и \<\= 64',
	'distribution_declaration_name_request_too_long' => 'Длина имени должна быть \>\= 3 и \<\= 64',
	'distribution_declaration_name_request_spaces' => "Разрешено использовать не более чем 2 пробела",
	'distribution_declaration_name_request_restricted_characters_title' => "Запрещены любые символы кроме букв",
	'distribution_declaration_name_request_restricted_characters_description' => "Удали эти символы:",
	'distribution_declaration_name_update_success' => 'Название заменено:',
	'distribution_declaration_name_update_fail' => 'Не удалось заменить название',
	'distribution_declaration_button_location' => 'Местоположение',
	'distribution_declaration_button_location_send' => 'Отправить местоположение',
	'distribution_declaration_location_send_title' => 'Отправь местоположение',
	'distribution_declaration_location_send_description' => "У тебя появилась кнопка на основной клавиатуре\nПри нажатии на неё можно будет выбрать локацию на карте\n\n*Пришли широту и долготу в формате:* 50\.969043, 9\.797588",
	'distribution_declaration_location_send_not_acceptable' => 'Не удалось обработать местоположение',
	'distribution_declaration_location_send_latitude_too_small' => 'Широта должна быть \>\= 0 и \<\=90',
	'distribution_declaration_location_send_latitude_too_big' => 'Широта должна быть \>\= 0 и \<\=90',
	'distribution_declaration_location_send_longitude_too_small' => 'Долгота должна быть \>\= 0 и \<\=180',
	'distribution_declaration_location_send_longitude_too_big' => 'Долгота должна быть \>\= 0 и \<\=180',
	'distribution_declaration_location_update_success' => 'Местоположение заменено:',
	'distribution_declaration_location_update_fail' => 'Не удалось заменить местоположение',
	'distribution_declaration_button_confirm' => 'Подтвердить',
	'distribution_declaration_button_cancel' => 'Отменить',

	// Локализация дистрибутива
	'distribution_localization_started' => 'Запущен процесс локализации дистрибутива',
	'distribution_localization_continiued' => 'Найден и продолжен процесс локализации дистрибутива',
	'distribution_localization_created' => 'Создана запись локализации дистрибутива в базе данных',
	'distribution_localization_not_created' => 'Не удалось создать запись локализации дистрибутива в базе данных',
	'distribution_localization_select_language_title' => 'Выбери язык',
	'distribution_localization_select_language_description' => "Выбранный язык позволит создать локализацию для пользователей с таким же языком\n\nТы можешь создать 1 локализацию для каждого языка",

	// Поиск дистрибутива
	'distribution_search_started' => 'Процесс поиска дистрибутива запущен',
	'distribution_search_not_started' => 'Процесс поиска дистрибутива не запущен',
	'distribution_search_ended' => 'Процесс поиска дистрибутива завершён',
	'distribution_search_not_localized' => 'Не удалось инициализировать локализацию дистрибутива',
	'distribution_search_not_named' => 'Нет названия',
	'distribution_search_continiued' => 'Процесс поиска дистрибутива найден и продолжен',
	'distribution_search_empty' => 'Не найдены дистрибутивы',
	'distribution_search_title' => 'Поиск дистрибутива',
	'distribution_search_memberships' => 'Участники',
	'distribution_search_recognized' => 'Признанные',
	'distribution_search_planners' => 'Планирующие',
	'distribution_search_volunteers' => 'Волонтёры',
	'distribution_search_messages' => 'Сообщения',
	'distribution_search_location' => 'Местоположение',
	'distribution_search_page_next_exists' => 'В реестре есть ещё дистрибутивы',
	'distribution_search_page_next_not_exists' => 'В реестре больше нет дистрибутивов',
	'distribution_search_button_name' => 'Название',
	'distribution_search_name_request_title' => 'Введи название',
	'distribution_search_name_request_description' => 'Поиск будет проводиться по названиям с использованием функции Левенштейна',
	'distribution_search_name_request_not_acceptable' => 'Не удалось обработать название',
	'distribution_search_name_request_too_short' => 'Длина названия должна быть \>\= 3 и \<\= 64',
	'distribution_search_name_request_too_long' => 'Длина названия должна быть \>\= 3 и \<\= 64',
	'distribution_search_name_request_restricted_characters_title' => "Запрещены любые символы кроме букв",
	'distribution_search_name_request_restricted_characters_description' => "Удали эти символы:",
	'distribution_search_name_update_success' => 'Название заменено:',
	'distribution_search_name_update_fail' => 'Не удалось заменить название',
	'distribution_search_button_location' => 'Местоположение',
	'distribution_search_button_location_send' => 'Отправить местоположение',
	'distribution_search_location_send_title' => 'Отправь местоположение',
	'distribution_search_location_send_description' => "У тебя появилась кнопка на основной клавиатуре\nПри нажатии на неё можно будет выбрать локацию на карте\n\n*Пришли широту и долготу в формате:* 50\.969043, 9\.797588",
	'distribution_search_location_send_not_acceptable' => 'Не удалось обработать местоположение',
	'distribution_search_location_send_latitude_too_small' => 'Широта должна быть \>\= 0 и \<\=90',
	'distribution_search_location_send_latitude_too_big' => 'Широта должна быть \>\= 0 и \<\=90',
	'distribution_search_location_send_longitude_too_small' => 'Долгота должна быть \>\= 0 и \<\=180',
	'distribution_search_location_send_longitude_too_big' => 'Долгота должна быть \>\= 0 и \<\=180',
	'distribution_search_location_update_success' => 'Местоположение заменено:',
	'distribution_search_location_update_fail' => 'Не удалось заменить местоположение',
	'distribution_search_button_distance' => 'Расстояние',
	'distribution_search_distance_request_title' => 'Введи расстояние',
	'distribution_search_distance_request_description' => 'Поиск будет производиться в радиусе от этого значения по формуле Винсенти',
	'distribution_search_distance_request_not_acceptable' => 'Не удалось обработать расстояние',
	'distribution_search_distance_request_too_short_km' => 'Длина расстояния должна быть \>\= 0 и \<\= 600',
	'distribution_search_distance_request_too_long_km' => 'Длина расстояния должна быть \>\= 0 и \<\= 600',
	'distribution_search_distance_request_restricted_characters_title' => "Запрещены любые символы кроме цифр",
	'distribution_search_distance_request_restricted_characters_description' => "Удали эти символы:",
	'distribution_search_distance_update_success' => 'Расстояние заменено:',
	'distribution_search_distance_update_fail' => 'Не удалось заменить расстояние',
	'distribution_search_button_start' => 'Начать поиск',
	'distribution_search_button_end' => 'Завершить поиск',
	'distribution_search_button_page_next' => 'Следующая страница',
	'distribution_search_button_map' => 'Карта',
	'distribution_search_button_memberships' => 'Участники',
	'distribution_search_button_volunteers' => 'Волонтёры',
	'distribution_search_button_plan' => 'Запланировать',
	'distribution_search_button_unplan' => 'Отменить планирование',
	'distribution_search_planned' => 'Ты запланировал вступление в дистрибутив',
	'distribution_search_already_planned' => 'Ты уже запланировал вступление в дистрибутив',
	'distribution_search_unplanned' => 'Ты отменил запланированное вступление в дистрибутив',
	'distribution_search_already_unplanned' => 'Ты уже отменил запланировал вступление в дистрибутив',
	'distribution_search_button_join' => 'Присоединиться',
	'distribution_search_button_leave' => 'Покинуть',
	'distribution_search_joined_title' => 'Ты вступил в дистрибутив',
	'distribution_search_joined_description' => 'Ты заявил о том, что являешься структором дистрибутива',
	'distribution_search_already_joined' => 'Ты уже заявил себя структором дистрибутива',
	'distribution_search_leaved' => 'Ты покинул дистрибутив',
	'distribution_search_already_leaved' => 'Ты уже покинул дистрибутив',
	'distribution_search_button_message' => 'Сообщение',
	'distribution_search_km' => 'км',
	'distribution_search_mi' => 'мл',
	'distribution_search_membership_not_updated' => 'Не удалось обновить запись участника дистрибутива в базе данных',
	'distribution_search_membership_not_created' => 'Не удалось создать запись участника дистрибутива в базе данных',
	'distribution_search_distribution_not_initialized' => 'Не удалось инициализировать дистрибутив',
	'distribution_search_message_not_initialized' => 'Не удалось инициализировать сообщение',
	'distribution_search_another_joined' => 'Ты уже являешься участником другого дистрибутива',
	'distribution_search_another_planned' => 'Ты уже планируешь вступить в другой дистрибутив',

	// Выбор дистрибутива
	'distribution_select_started' => 'Процесс выбора дистрибутива запущен',
	'distribution_select_not_started' => 'Процесс выбора дистрибутива не запущен',
	'distribution_select_ended' => 'Процесс выбора дистрибутива завершён',
	'distribution_select_not_localized' => 'Не удалось инициализировать локализацию дистрибутива',
	'distribution_select_not_named' => 'Нет названия',
	'distribution_select_continiued' => 'Процесс выбора дистрибутива найден и продолжен',
	'distribution_select_empty' => 'Не найдены дистрибутивы',
	'distribution_select_title' => 'Выбор дистрибутива',
	'distribution_select_page_next_exists' => 'В реестре есть ещё дистрибутивы',
	'distribution_select_page_next_not_exists' => 'В реестре больше нет дистрибутивов',
	'distribution_select_button_name' => 'Название',
	'distribution_select_name_request_title' => 'Введи название',
	'distribution_select_name_request_description' => 'выбор будет проводиться по названиям с использованием функции Левенштейна',
	'distribution_select_name_request_not_acceptable' => 'Не удалось обработать название',
	'distribution_select_name_request_too_short' => 'Длина названия должна быть \>\= 3 и \<\= 64',
	'distribution_select_name_request_too_long' => 'Длина названия должна быть \>\= 3 и \<\= 64',
	'distribution_select_name_request_restricted_characters_title' => "Запрещены любые символы кроме букв",
	'distribution_select_name_request_restricted_characters_description' => "Удали эти символы:",
	'distribution_select_name_update_success' => 'Название заменено:',
	'distribution_select_name_update_fail' => 'Не удалось заменить название',
	'distribution_select_button_location' => 'Местоположение',
	'distribution_select_button_location_send' => 'Отправить местоположение',
	'distribution_select_location_send_title' => 'Отправь местоположение',
	'distribution_select_location_send_description' => "У тебя появилась кнопка на основной клавиатуре\nПри нажатии на неё можно будет выбрать локацию на карте\n\n*Пришли широту и долготу в формате:* 50\.969043, 9\.797588",
	'distribution_select_location_send_not_acceptable' => 'Не удалось обработать местоположение',
	'distribution_select_location_send_latitude_too_small' => 'Широта должна быть \>\= 0 и \<\=90',
	'distribution_select_location_send_latitude_too_big' => 'Широта должна быть \>\= 0 и \<\=90',
	'distribution_select_location_send_longitude_too_small' => 'Долгота должна быть \>\= 0 и \<\=180',
	'distribution_select_location_send_longitude_too_big' => 'Долгота должна быть \>\= 0 и \<\=180',
	'distribution_select_location_update_success' => 'Местоположение заменено:',
	'distribution_select_location_update_fail' => 'Не удалось заменить местоположение',
	'distribution_select_button_distance' => 'Расстояние',
	'distribution_select_distance_request_title' => 'Введи расстояние',
	'distribution_select_distance_request_description' => 'Поиск будет производиться в радиусе от этого значения по формуле Винсенти',
	'distribution_select_distance_request_not_acceptable' => 'Не удалось обработать расстояние',
	'distribution_select_distance_request_too_short_km' => 'Длина расстояния должна быть \>\= 0 и \<\= 600',
	'distribution_select_distance_request_too_long_km' => 'Длина расстояния должна быть \>\= 0 и \<\= 600',
	'distribution_select_distance_request_restricted_characters_title' => "Запрещены любые символы кроме цифр",
	'distribution_select_distance_request_restricted_characters_description' => "Удали эти символы:",
	'distribution_select_distance_update_success' => 'Расстояние заменено:',
	'distribution_select_distance_update_fail' => 'Не удалось заменить расстояние',
	'distribution_select_button_select' => 'Выбрать',
	'distribution_select_button_cancel' => 'Отменить выбор',
	'distribution_select_button_page_next' => 'Следующая страница',

	// Организация
	'organisation_title' => 'Организация',
	'organisation_description' => 'Интернациональное объединение всех кто хочет жить честно и свободно, где никто ни от кого ничего не требует и ни к чему не принуждает',
	'organisation_structor' => '*Структор* \- анархист, представляющий дистрибутив',
	'organisation_autonom' => '*Автоном* \- анархист, представляющий только себя лично',
	'organisation_warning_legal' => 'Не делайте ничего, что нарушает закон страны в которой вы находитесь, не доверяйте никому и думайте своей головой',
	'organisation_warning_administration' => 'На данном этапе развития проекта Антивертикаль администрация сохраняет за собой право единолично принимать решение по удалению потенциально опасных для организации и её участников материалов',
	'organisation_button_help' => 'Помощь',
	'organisation_button_investor' => 'Инвестор',
	'organisation_button_volunteer' => 'Волонтёр',
	'organisation_button_structor' => 'Структор',
	'organisation_button_structor_distribution' => 'Дистрибутив',
	'organisation_button_autonom' => 'Автоном',

	// Аккаунт
	'account_title' => 'Аккаунт',
	'account_identifier' => 'Идентификатор',
	'account_export' => 'Доступен экспорт в основную блокчейн сеть',
	/* 'account_data' => "⚠️ Твои данные могут быть выданы спецслужбам России\nБудь осторожен и думай своей головой",
	'account_security_repository' => 'Информационная безопасность',
	'account_security_repository_mirror_github' => 'зеркало', */
	'account_authorized_system' => 'Доступ к системе',
	'account_authorized_messages' => 'Доступ к сообщениям',
	'account_authorized_authonom' => 'Становиться автономом',
	'account_authorized_structor' => 'Становиться структором',
	'account_authorized_volunteer' => 'Становиться волонтёром',
	'account_authorized_investor' => 'Становиться инвестором',
	'account_authorized_recruiter' => 'Становиться вербовщиком',
	'account_authorized_relations' => 'Доступ к отношениям',
	'account_authorized_settings' => 'Доступ к настройкам',
	'account_authorized_system_accounts' => 'Доступ к системе аккаунтов',
	'account_authorized_system_distributions' => 'Доступ к системе дистрибутивов',
	'account_authorized_system_settings' => 'Доступ к системным настройкам',
	'account_button_localizations' => 'Локализации',
	'account_localization_create_failted_to_initialize_language' => 'Не удалось инициализировать язык',

	'account_localization_title' => 'Локализации',
	'account_localization_amount' => 'Количество',
	'account_localization_create' => 'Создать локализацию',
	'account_localization_create_started' => 'Процесс создания локализации аккаунта запущен',
	'account_localization_create_not_started' => 'Процесс создания локализации аккаунта не запущен',
	'account_localization_create_ended' => 'Процесс создания локализации аккаунта завершён',
	'account_localization_create_continiued' => 'Процесс создания локализации аккаунта найден и продолжен',
	'account_localization_create_generation' => 'Генерация записи локализации аккаунта',
	'account_localization_create_created' => 'Создана запись локализации аккаунта в базе данных',
	'account_localization_create_canceled' => 'Процесс создания локализации аккаунта отменён',
	'account_localization_create_completed' => 'Процесс создания локализации аккаунта завершен',
	'account_localization_create_not_created' => 'Не удалось создать запись локализации аккаунта в базе данных',
	'account_localization_create_every_language_created' => 'Для всех существующих в реестре языков уже были созданы локализации',
	'account_localization_create_button_language' => 'Язык',
	'account_localization_create_select_language_title' => 'Выбери язык',
	'account_localization_create_select_language_description' => "Выбранный язык будет использован при создания локализации аккаунта\n\nТы можешь создать 1 локализацию для каждого языка",
	'account_localization_create_language_update_success' => 'Язык заменён:',
	'account_localization_create_language_update_fail' => 'Не удалось заменить язык',
	'account_localization_create_button_name' => 'Имя',
	'account_localization_create_name_request' => 'Введи имя',
	'account_localization_create_name_request_not_acceptable' => 'Не удалось обработать имя',
	'account_localization_create_name_request_too_short' => 'Длина имени должна быть \>\= 2 и \<\= 128',
	'account_localization_create_name_request_too_long' => 'Длина имени должна быть \>\= 2 и \<\= 128',
	'account_localization_create_name_request_restricted_characters_title' => "Запрещены любые символы кроме букв, тире и пробелов",
	'account_localization_create_name_request_restricted_characters_description' => "Удали эти символы:",
	'account_localization_create_name_update_success' => 'Имя заменено:',
	'account_localization_create_name_update_fail' => 'Не удалось заменить имя',
	'account_localization_create_button_confirm' => 'Подтвердить',
	'account_localization_create_button_cancel' => 'Отменить',
	'account_localization_update_started' => 'Процесс обновления локализации аккаунта запущен',
	'account_localization_update_not_started' => 'Процесс обновления локализации аккаунта не запущен',
	'account_localization_update_ended' => 'Процесс обновления локализации аккаунта завершён',
	'account_localization_update_continiued' => 'Процесс обновления локализации аккаунта найден и продолжен',
	'account_localization_update_generation' => 'Генерация записи локализации аккаунта',
	'account_localization_update_generation_target' => 'Редактирование',
	'account_localization_update_updated' => 'Обновлена запись локализации аккаунта в базе данных',
	'account_localization_update_canceled' => 'Процесс обновления локализации аккаунта отменён',
	'account_localization_update_completed' => 'Процесс обновления локализации аккаунта завершен',
	'account_localization_update_not_updated' => 'Не удалось обновить запись локализации аккаунта в базе данных',
	'account_localization_update_not_initialized_localization' => 'Не удалось инициализировать локализацию аккаунта из базы данных',
	'account_localization_update_button_name' => 'Имя',
	'account_localization_update_name_request' => 'Введи имя',
	'account_localization_update_name_request_not_acceptable' => 'Не удалось обработать имя',
	'account_localization_update_name_request_too_short' => 'Длина имени должна быть \>\= 2 и \<\= 128',
	'account_localization_update_name_request_too_long' => 'Длина имени должна быть \>\= 2 и \<\= 128',
	'account_localization_update_name_request_restricted_characters_title' => "Запрещены любые символы кроме букв, тире и пробелов",
	'account_localization_update_name_request_restricted_characters_description' => "Удали эти символы:",
	'account_localization_update_name_update_success' => 'Имя заменено:',
	'account_localization_update_name_update_fail' => 'Не удалось заменить имя',
	'account_localization_update_button_confirm' => 'Подтвердить',
	'account_localization_update_button_cancel' => 'Отменить',
	'account_localization_search' => 'Поиск',

	// Настройки языка
	'settings_select_language_title' => 'Выбери язык',
	'settings_select_language_description' => 'Выбранный язык будет записан в настройки аккаунта',
	'settings_language_update_success' => 'Язык заменён:',
	'settings_language_update_fail' => 'Не удалось заменить язык',

	// Выбор языка
	'select_language_title' => 'Выбери язык',
	'select_language_description' => 'Выбранный язык будет использован в текущем процессе',
	'select_language_button_add' => 'Добавить язык',

	// Репозиторий
	'repository_title' => 'Репозиторий',
	'repository_text' => <<<TXT
	Svoboder написан на [PHP](https://www.php.net/) используя [Zanzara](https://github.com/badfarm/zanzara) для Telegram,
	мой [MINIMAL](https://git.svoboda.works/mirzaev/minimal) фреймворк для PHP и моя база данных [Baza](https://git.svoboda.works/mirzaev/baza)

	Код находится под лицензией [WTFPL](https://en.wikipedia.org/wiki/WTFPL)
	Помогай с разработкой или используй мой код бесплатно\!
	TXT,
	'repository_button_code' => 'Код',
	'repository_button_issues' => 'Проблемы',
	'repository_button_suggestions' => 'Предложения',

	// Автор
	'author_title' => 'Автор',
	'author_text' => <<<TXT
	*Арсен Мирзаев Татьяно\-Мурадович*
	Программист, анархист, вегетарианец
	TXT,
	'author_button_neurojournal' => 'Нейрожурнал',
	'author_button_projects' => 'Проекты',
	'author_button_twitter' => 'Twitter',
	'author_button_bluesky' => 'Bluesky',
	'author_button_bastyon' => 'Bastyon',
	'author_button_youtube_english' => 'YouTube',
	'author_button_youtube_russian' => 'YouTube',
	'author_button_message' => 'Отправить сообщение',

	// Авторизация
	'not_authorized_system' => 'У тебя нет доступа к системе',
	'not_authorized_messages' => 'У тебя нет доступа к сообщениям',
	'not_authorized_joins' => 'У тебя нет доступа к вступлениям',
	'not_authorized_settings' => 'У тебя нет доступа к настройкам',
	'not_authorized_system_settings' => 'У тебя нет доступа к системным настройкам',
	'not_authorized_system_distributions' => 'У тебя нет доступа к администрированию дистрибутивов',

	// Прочее
	'why_so_shroomious' => 'почему такой грибъёзный',
];
