<?php
define('MENU_MEMBERSHIPS_AMOUNT', 10000000);

define('DISTRIBUTIONS_SEARCH_PAGE', 3);
define('DISTRIBUTIONS_SEARCH_DISTRIBUTION_DISTANCE', 300);
define('DISTRIBUTIONS_SEARCH_DISTRIBUTION_LOCALIZATIONS_AMOUNT', 100);
define('DISTRIBUTIONS_SEARCH_DISTRIBUTION_NAME_LEVENSHTEIN_DISTANCE', 4);
define('DISTRIBUTIONS_SEARCH_MEMBERSHIP_DEPRECATING_RECORDS_AMOUNT', 500);
define('DISTRIBUTIONS_SEARCH_MEMBERSHIPS_AMOUNT', 10000000);

define('DISTRIBUTIONS_SELECT_PAGE', 10);
define('DISTRIBUTIONS_SELECT_DISTRIBUTION_DISTANCE', 300);
define('DISTRIBUTIONS_SELECT_DISTRIBUTION_LOCALIZATIONS_AMOUNT', 100);
define('DISTRIBUTIONS_SELECT_DISTRIBUTION_NAME_LEVENSHTEIN_DISTANCE', 4);
define('DISTRIBUTIONS_SELECT_MEMBERSHIP_DEPRECATING_RECORDS_AMOUNT', 500);
define('DISTRIBUTIONS_SELECT_MEMBERSHIPS_AMOUNT', 10000000);

define('MEMBERSHIPS_SEARCH_PAGE', 3);
define('MEMBERSHIPS_SEARCH_DISTRIBUTION_LOCALIZATIONS_AMOUNT', 100);
define('MEMBERSHIPS_SEARCH_ACCOUNT_LOCALIZATIONS_AMOUNT', 100);
define('MEMBERSHIPS_SEARCH_MEMBERSHIP_NAME_LEVENSHTEIN_DISTANCE', 4);
define('MEMBERSHIPS_SEARCH_STATUS_ROW_AMOUNT', 3);

define('ACCOUNT_LOCALIZATION_ACCOUNT_LOCALIZATIONS_AMOUNT', 100);
define('ACCOUNT_LOCALIZATION_CREATE_ACCOUNT_LOCALIZATIONS_AMOUNT', 100);

define('ACCOUNT_ACCESS_SYSTEM', 1);
define('ACCOUNT_ACCESS_MESSAGES', 1);
define('ACCOUNT_ACCESS_AUTHONOM', 1);
define('ACCOUNT_ACCESS_STRUCTOR', 1);
define('ACCOUNT_ACCESS_VOLUNTEER', 1);
define('ACCOUNT_ACCESS_INVESTOR', 1);
define('ACCOUNT_ACCESS_RECRUITER', 1);
define('ACCOUNT_ACCESS_SETTINGS', 1);
define('ACCOUNT_ACCESS_SYSTEM_ACCOUNTS', 0);
define('ACCOUNT_ACCESS_SYSTEM_DISTRIBUTIONS', 0);
define('ACCOUNT_ACCESS_SYSTEM_SETTINGS', 0);
